leftnav:
- identifier: bba3544a-e37f-42ac-8595-3b60a13b8432
  name: Marguerite de Navarre Society Website
  pageRef: /external-resources/marguerite-de-navarre-society-website_bba3544a-e37f-42ac-8595-3b60a13b8432
  weight: 10
